### ISSUE TITLE
Crashes the server with client side code

### ISSUE THREAD

**Issue by XxsjrapsxX** [Dekunutter/CherryBlossomGrotto#10] opened 2022-05-04 07:27 UTC
this mod contains client side code causing the mod to crash when used on servers, which is sad as i wished to use it in a pack of mine but will now be forced to remove it, here is the log file for the issue, hope it will help fix this issue in the futur
[latest (2).log](https://github.com/Dekunutter/CherryBlossomGrotto/files/8618528/latest.2.log)
e

**Comment by Dekunutter** [comment] 2022-05-04 13:23
Thanks for bringing this to my attention. Just popped this code out a few hours prior but I see where the issue is. I'll be working on a fix this week

**Comment by Dekunutter** [comment] 2022-05-05 03:48
This has been fixed now. Some client-only renderers were being registered server-side causing issues with server initialization. I have fixed this in v1.3 so I will close out this issue is resolved

**Closed by Dekunutter** 2022-05-05 03:48 UTC
