### ISSUE TITLE
Crash on Startup with Latest Patch

### ISSUE THREAD

**Issue by WelpSTudent** [Dekunutter/CherryBlossomGrotto#14] opened 2022-05-09 03:34 UTC
https://pastebin.com/CNeh5ptL

**Comment by Dekunutter** [comment] 2022-05-09 04:18
I haven't managed to reproduce this one on my end yet. Downloaded the mod on 0.4.1 (latest beta release) and ran it with Patchouli, Botania, AIOTBotania, Curios and TerraBlender on their latest versions and everything seemed fine. No conflicts.

You are running a slightly newer version forge and there's a lot of mods in that list that could possibly be causing some sort of conflict. I'll look into it more after work tomorrow but so far I havent been able to see a clear cause here

**Comment by Dekunutter** [comment] 2022-05-10 03:06
Dived deeper today so leaving some notes but don't have any indication on why this happened yet:

Tried this with a list of about 20~ other mods installed. Used Forge 1.18.2 - 40.1.16 like the stack trace. Everything loaded just fine, no crash on startup and was able to generate a fresh world without issue.

Trace implicates an issue loading the cherry blossom trunk placer and then registering a null object in its place. Given crash report does not contain any logging outputs that should trigger from my trunk placer initialization code when something goes awry so dont have much information that I can gleam from this right now

**Comment by Dekunutter** [comment] 2022-07-14 01:24
Recently pushed a fix for the 1.19.0 version of this mod that was caused by compatibility issues with Ars Nouveau. Will try to replicate the compatibility issue and fix the 1.18.2 version this week.

**Comment by Dekunutter** [comment] 2022-07-18 04:36
Version v0.4.2 of the 1.18 mod now has a fix for this. Reverts tree trunk generation back to vanilla params to improve inter-mod compatibility. Resolving this issue

**Closed by Dekunutter** 2022-07-18 04:36 UTC
